const expressions = [
  { termKey: "exp_head_clouds_term", meaningKey: "exp_head_clouds_meaning", exampleKey: "exp_head_clouds_example" },
  { termKey: "exp_rain_wet_term", meaningKey: "exp_rain_wet_meaning", exampleKey: "exp_rain_wet_example" },
  { termKey: "exp_cost_eyes_term", meaningKey: "exp_cost_eyes_meaning", exampleKey: "exp_cost_eyes_example" },
  { termKey: "exp_ace_it_term", meaningKey: "exp_ace_it_meaning", exampleKey: "exp_ace_it_example" },
  { termKey: "exp_troll_term", meaningKey: "exp_troll_meaning", exampleKey: "exp_troll_example" },
  { termKey: "exp_cringe_term", meaningKey: "exp_cringe_meaning", exampleKey: "exp_cringe_example" },
  { termKey: "exp_cookie_seeker_term", meaningKey: "exp_cookie_seeker_meaning", exampleKey: "exp_cookie_seeker_example" },
  { termKey: "exp_be_cool_term", meaningKey: "exp_be_cool_meaning", exampleKey: "exp_be_cool_example" },
  { termKey: "exp_go_overboard_term", meaningKey: "exp_go_overboard_meaning", exampleKey: "exp_go_overboard_example" },
  { termKey: "exp_take_the_blame_term", meaningKey: "exp_take_the_blame_meaning", exampleKey: "exp_take_the_blame_example" },
  { termKey: "exp_swallow_frog_term", meaningKey: "exp_swallow_frog_meaning", exampleKey: "exp_swallow_frog_example" },
  { termKey: "exp_get_pissed_term", meaningKey: "exp_get_pissed_meaning", exampleKey: "exp_get_pissed_example" },
  { termKey: "exp_go_wrong_term", meaningKey: "exp_go_wrong_meaning", exampleKey: "exp_go_wrong_example" },
  { termKey: "exp_be_real_term", meaningKey: "exp_be_real_meaning", exampleKey: "exp_be_real_example" },
  { termKey: "exp_no_time_brother_term", meaningKey: "exp_no_time_brother_meaning", exampleKey: "exp_no_time_brother_example" },
  { termKey: "exp_crush_term", meaningKey: "exp_crush_meaning", exampleKey: "exp_crush_example" },
  { termKey: "exp_ship_term", meaningKey: "exp_ship_meaning", exampleKey: "exp_ship_example" },
  { termKey: "exp_flop_term", meaningKey: "exp_flop_meaning", exampleKey: "exp_flop_example" },
  { termKey: "exp_slay_term", meaningKey: "exp_slay_meaning", exampleKey: "exp_slay_example" },
  { termKey: "exp_bounce_term", meaningKey: "exp_bounce_meaning", exampleKey: "exp_bounce_example" },
  { termKey: "exp_throw_in_towel_term", meaningKey: "exp_throw_in_towel_meaning", exampleKey: "exp_throw_in_towel_example" },
  { termKey: "exp_be_shocked_term", meaningKey: "exp_be_shocked_meaning", exampleKey: "exp_be_shocked_example" },
  { termKey: "exp_drop_ball_term", meaningKey: "exp_drop_ball_meaning", exampleKey: "exp_drop_ball_example" },
  { termKey: "exp_ghost_someone_term", meaningKey: "exp_ghost_someone_meaning", exampleKey: "exp_ghost_someone_example" },
  { termKey: "exp_left_hanging_term", meaningKey: "exp_left_hanging_meaning", exampleKey: "exp_left_hanging_example" },
  { termKey: "exp_storm_in_teacup_term", meaningKey: "exp_storm_in_teacup_meaning", exampleKey: "exp_storm_in_teacup_example" },
  { termKey: "exp_find_a_way_term", meaningKey: "exp_find_a_way_meaning", exampleKey: "exp_find_a_way_example" },
  { termKey: "exp_break_ice_term", meaningKey: "exp_break_ice_meaning", exampleKey: "exp_break_ice_example" },
  { termKey: "exp_go_downhill_term", meaningKey: "exp_go_downhill_meaning", exampleKey: "exp_go_downhill_example" },
  { termKey: "exp_suck_up_term", meaningKey: "exp_suck_up_meaning", exampleKey: "exp_suck_up_example" },
  { termKey: "exp_fill_time_term", meaningKey: "exp_fill_time_meaning", exampleKey: "exp_fill_time_example" },
  { termKey: "exp_lie_low_term", meaningKey: "exp_lie_low_meaning", exampleKey: "exp_lie_low_example" },
  { termKey: "exp_cause_a_stir_term", meaningKey: "exp_cause_a_stir_meaning", exampleKey: "exp_cause_a_stir_example" },
  { termKey: "exp_be_in_drought_term", meaningKey: "exp_be_in_drought_meaning", exampleKey: "exp_be_in_drought_example" },
  { termKey: "exp_make_fool_term", meaningKey: "exp_make_fool_meaning", exampleKey: "exp_make_fool_example" },
  { termKey: "exp_walk_eggshells_term", meaningKey: "exp_walk_eggshells_meaning", exampleKey: "exp_walk_eggshells_example" },
  { termKey: "exp_keep_eye_on_term", meaningKey: "exp_keep_eye_on_meaning", exampleKey: "exp_keep_eye_on_example" },
  { termKey: "exp_take_break_term", meaningKey: "exp_take_break_meaning", exampleKey: "exp_take_break_example" },
  { termKey: "exp_be_chill_term", meaningKey: "exp_be_chill_meaning", exampleKey: "exp_be_chill_example" },
  { termKey: "exp_jump_gun_term", meaningKey: "exp_jump_gun_meaning", exampleKey: "exp_jump_gun_example" },
  { termKey: "exp_give_it_gas_term", meaningKey: "exp_give_it_gas_meaning", exampleKey: "exp_give_it_gas_example" },
  { termKey: "exp_cry_spilled_milk_term", meaningKey: "exp_cry_spilled_milk_meaning", exampleKey: "exp_cry_spilled_milk_example" },
  { termKey: "exp_want_it_easy_term", meaningKey: "exp_want_it_easy_meaning", exampleKey: "exp_want_it_easy_example" },
  { termKey: "exp_went_bad_term", meaningKey: "exp_went_bad_meaning", exampleKey: "exp_went_bad_example" },
  { termKey: "exp_do_nothing_term", meaningKey: "exp_do_nothing_meaning", exampleKey: "exp_do_nothing_example" },
  { termKey: "exp_go_for_stroll_term", meaningKey: "exp_go_for_stroll_meaning", exampleKey: "exp_go_for_stroll_example" },
  { termKey: "exp_on_the_market_term", meaningKey: "exp_on_the_market_meaning", exampleKey: "exp_on_the_market_example" },
  { termKey: "exp_be_a_fan_term", meaningKey: "exp_be_a_fan_meaning", exampleKey: "exp_be_a_fan_example" },
  { termKey: "exp_give_shout_out_term", meaningKey: "exp_give_shout_out_meaning", exampleKey: "exp_give_shout_out_example" },
  { termKey: "exp_cry_a_river_term", meaningKey: "exp_cry_a_river_meaning", exampleKey: "exp_cry_a_river_example" },
  { termKey: "exp_turn_blind_eye_term", meaningKey: "exp_turn_blind_eye_meaning", exampleKey: "exp_turn_blind_eye_example" },
  { termKey: "exp_give_two_cents_term", meaningKey: "exp_give_two_cents_meaning", exampleKey: "exp_give_two_cents_example" },
  { termKey: "exp_throw_fit_term", meaningKey: "exp_throw_fit_meaning", exampleKey: "exp_throw_fit_example" },
  { termKey: "exp_king_in_belly_term", meaningKey: "exp_king_in_belly_meaning", exampleKey: "exp_king_in_belly_example" },
  { termKey: "exp_die_on_eve_term", meaningKey: "exp_die_on_eve_meaning", exampleKey: "exp_die_on_eve_example" },
  { termKey: "exp_cry_over_dead_calf_term", meaningKey: "exp_cry_over_dead_calf_meaning", exampleKey: "exp_cry_over_dead_calf_example" },
  { termKey: "exp_get_real_term", meaningKey: "exp_get_real_meaning", exampleKey: "exp_get_real_example" },
  { termKey: "exp_hold_candle_term", meaningKey: "exp_hold_candle_meaning", exampleKey: "exp_hold_candle_example" },
  { termKey: "exp_tie_knot_in_water_term", meaningKey: "exp_tie_knot_in_water_meaning", exampleKey: "exp_tie_knot_in_water_example" },
  { termKey: "exp_no_point_without_knot_term", meaningKey: "exp_no_point_without_knot_meaning", exampleKey: "exp_no_point_without_knot_example" },

  
];

const motivation = [
  "mot_01", "mot_02", "mot_03", "mot_04", "mot_05", "mot_06", "mot_07", "mot_08", "mot_09", "mot_10",
  "mot_11", "mot_12", "mot_13", "mot_14", "mot_15", "mot_16", "mot_17", "mot_18", "mot_19", "mot_20",
  "mot_21", "mot_22", "mot_23", "mot_24", "mot_25", "mot_26", "mot_27", "mot_28", "mot_29", "mot_30",
  "mot_31", "mot_32", "mot_33", "mot_34", "mot_35", "mot_36", "mot_37", "mot_38", "mot_39", "mot_40",
  "mot_41", "mot_42", "mot_43", "mot_44", "mot_45", "mot_46", "mot_47", "mot_48", "mot_49", "mot_50",
  "mot_51", "mot_52", "mot_53", "mot_54", "mot_55", "mot_56", "mot_57", "mot_58", "mot_59", "mot_60",
];

const bible = [
 "bib_01", "bib_02", "bib_03", "bib_04", "bib_05", "bib_06", "bib_07", "bib_08", "bib_09", "bib_10",
  "bib_11", "bib_12", "bib_13", "bib_14", "bib_15", "bib_16", "bib_17", "bib_18", "bib_19", "bib_20",
  "bib_21", "bib_22", "bib_23", "bib_24", "bib_25", "bib_26", "bib_27",
];

const challenges = {
  
  basic: [
    { titleKey: "cha_b_01_title", objKey: "cha_b_01_obj", stepKeys: ["cha_b_01_step1", "cha_b_01_step2", "cha_b_01_step3"], extraKey: "cha_b_01_extra" },
    { titleKey: "cha_b_02_title", objKey: "cha_b_02_obj", stepKeys: ["cha_b_02_step1", "cha_b_02_step2", "cha_b_02_step3"], extraKey: "cha_b_02_extra" },
    { titleKey: "cha_b_03_title", objKey: "cha_b_03_obj", stepKeys: ["cha_b_03_step1", "cha_b_03_step2", "cha_b_03_step3", "cha_b_03_step4"], extraKey: "cha_b_03_extra" },
    { titleKey: "cha_b_04_title", objKey: "cha_b_04_obj", stepKeys: ["cha_b_04_step1", "cha_b_04_step2", "cha_b_04_step3"], extraKey: "cha_b_04_extra" },
    { titleKey: "cha_b_05_title", objKey: "cha_b_05_obj", stepKeys: ["cha_b_05_step1", "cha_b_05_step2", "cha_b_05_step3"], extraKey: "cha_b_05_extra" },
    { titleKey: "cha_b_06_title", objKey: "cha_b_06_obj", stepKeys: ["cha_b_06_step1", "cha_b_06_step2", "cha_b_06_step3"], extraKey: "cha_b_06_extra" },
    { titleKey: "cha_b_07_title", objKey: "cha_b_07_obj", stepKeys: ["cha_b_07_step1", "cha_b_07_step2", "cha_b_07_step3"], extraKey: "cha_b_07_extra" },
    { titleKey: "cha_b_08_title", objKey: "cha_b_08_obj", stepKeys: ["cha_b_08_step1", "cha_b_08_step2", "cha_b_08_step3"], extraKey: "cha_b_08_extra" },
    { titleKey: "cha_b_09_title", objKey: "cha_b_09_obj", stepKeys: ["cha_b_09_step1", "cha_b_09_step2", "cha_b_09_step3"], extraKey: "cha_b_09_extra" },
    { titleKey: "cha_b_10_title", objKey: "cha_b_10_obj", stepKeys: ["cha_b_10_step1", "cha_b_10_step2", "cha_b_10_step3", "cha_b_10_step4"], extraKey: "cha_b_10_extra" },
    { titleKey: "cha_b_11_title", objKey: "cha_b_11_obj", stepKeys: ["cha_b_11_step1", "cha_b_11_step2", "cha_b_11_step3"], extraKey: "cha_b_11_extra" },
    { titleKey: "cha_b_12_title", objKey: "cha_b_12_obj", stepKeys: ["cha_b_12_step1", "cha_b_12_step2", "cha_b_12_step3"], extraKey: "cha_b_12_extra" },
    { titleKey: "cha_b_13_title", objKey: "cha_b_13_obj", stepKeys: ["cha_b_13_step1", "cha_b_13_step2", "cha_b_13_step3"], extraKey: "cha_b_13_extra" },
    { titleKey: "cha_b_14_title", objKey: "cha_b_14_obj", stepKeys: ["cha_b_14_step1", "cha_b_14_step2", "cha_b_14_step3"], extraKey: "cha_b_14_extra" },
    { titleKey: "cha_b_15_title", objKey: "cha_b_15_obj", stepKeys: ["cha_b_15_step1", "cha_b_15_step2", "cha_b_15_step3"], extraKey: "cha_b_15_extra" },
    { titleKey: "cha_b_16_title", objKey: "cha_b_16_obj", stepKeys: ["cha_b_16_step1", "cha_b_16_step2", "cha_b_16_step3"], extraKey: "cha_b_16_extra" },
    { titleKey: "cha_b_17_title", objKey: "cha_b_17_obj", stepKeys: ["cha_b_17_step1", "cha_b_17_step2", "cha_b_17_step3"], extraKey: "cha_b_17_extra" },
    { titleKey: "cha_b_18_title", objKey: "cha_b_18_obj", stepKeys: ["cha_b_18_step1", "cha_b_18_step2", "cha_b_18_step3"], extraKey: "cha_b_18_extra" },
    { titleKey: "cha_b_19_title", objKey: "cha_b_19_obj", stepKeys: ["cha_b_19_step1", "cha_b_19_step2", "cha_b_19_step3"], extraKey: "cha_b_19_extra" },
    { titleKey: "cha_b_20_title", objKey: "cha_b_20_obj", stepKeys: ["cha_b_20_step1", "cha_b_20_step2", "cha_b_20_step3"], extraKey: "cha_b_20_extra" }
  ],
  communication: [
    
    { titleKey: "cha_c_01_title", objKey: "cha_c_01_obj", stepKeys: ["cha_c_01_step1", "cha_c_01_step2", "cha_c_01_step3"], extraKey: "cha_c_01_extra" },
    { titleKey: "cha_c_02_title", objKey: "cha_c_02_obj", stepKeys: ["cha_c_02_step1", "cha_c_02_step2", "cha_c_02_step3"], extraKey: "cha_c_02_extra" },
    { titleKey: "cha_c_03_title", objKey: "cha_c_03_obj", stepKeys: ["cha_c_03_step1", "cha_c_03_step2", "cha_c_03_step3"], extraKey: "cha_c_03_extra" },
    { titleKey: "cha_c_04_title", objKey: "cha_c_04_obj", stepKeys: ["cha_c_04_step1", "cha_c_04_step2", "cha_c_04_step3"], extraKey: "cha_c_04_extra" },
    { titleKey: "cha_c_05_title", objKey: "cha_c_05_obj", stepKeys: ["cha_c_05_step1", "cha_c_05_step2", "cha_c_05_step3"], extraKey: "cha_c_05_extra" },
    { titleKey: "cha_c_06_title", objKey: "cha_c_06_obj", stepKeys: ["cha_c_06_step1", "cha_c_06_step2", "cha_c_06_step3"], extraKey: "cha_c_06_extra" },
    { titleKey: "cha_c_07_title", objKey: "cha_c_07_obj", stepKeys: ["cha_c_07_step1", "cha_c_07_step2", "cha_c_07_step3"], extraKey: "cha_c_07_extra" },
    { titleKey: "cha_c_08_title", objKey: "cha_c_08_obj", stepKeys: ["cha_c_08_step1", "cha_c_08_step2", "cha_c_08_step3"], extraKey: "cha_c_08_extra" },
    { titleKey: "cha_c_09_title", objKey: "cha_c_09_obj", stepKeys: ["cha_c_09_step1", "cha_c_09_step2", "cha_c_09_step3"], extraKey: "cha_c_09_extra" },
    { titleKey: "cha_c_10_title", objKey: "cha_c_10_obj", stepKeys: ["cha_c_10_step1", "cha_c_10_step2", "cha_c_10_step3"], extraKey: "cha_c_10_extra" },
    { titleKey: "cha_c_11_title", objKey: "cha_c_11_obj", stepKeys: ["cha_c_11_step1", "cha_c_11_step2", "cha_c_11_step3"], extraKey: "cha_c_11_extra" },
    { titleKey: "cha_c_12_title", objKey: "cha_c_12_obj", stepKeys: ["cha_c_12_step1", "cha_c_12_step2", "cha_c_12_step3", "cha_c_12_step4"], extraKey: "cha_c_12_extra" },
    { titleKey: "cha_c_13_title", objKey: "cha_c_13_obj", stepKeys: ["cha_c_13_step1", "cha_c_13_step2", "cha_c_13_step3", "cha_c_13_step4"], extraKey: "cha_c_13_extra" },
    { titleKey: "cha_c_14_title", objKey: "cha_c_14_obj", stepKeys: ["cha_c_14_step1", "cha_c_14_step2", "cha_c_14_step3"], extraKey: "cha_c_14_extra" },
    { titleKey: "cha_c_15_title", objKey: "cha_c_15_obj", stepKeys: ["cha_c_15_step1", "cha_c_15_step2", "cha_c_15_step3", "cha_c_15_step4"], extraKey: "cha_c_15_extra" },
    { titleKey: "cha_c_16_title", objKey: "cha_c_16_obj", stepKeys: ["cha_c_16_step1", "cha_c_16_step2", "cha_c_16_step3"], extraKey: "cha_c_16_extra" },
    { titleKey: "cha_c_17_title", objKey: "cha_c_17_obj", stepKeys: ["cha_c_17_step1", "cha_c_17_step2", "cha_c_17_step3"], extraKey: "cha_c_17_extra" },
    { titleKey: "cha_c_18_title", objKey: "cha_c_18_obj", stepKeys: ["cha_c_18_step1", "cha_c_18_step2", "cha_c_18_step3"], extraKey: "cha_c_18_extra" },
    { titleKey: "cha_c_19_title", objKey: "cha_c_19_obj", stepKeys: ["cha_c_19_step1", "cha_c_19_step2", "cha_c_19_step3", "cha_c_19_step4"], extraKey: "cha_c_19_extra" }

  ],
  understanding: [
    
    { titleKey: "cha_u_01_title", objKey: "cha_u_01_obj", stepKeys: ["cha_u_01_step1", "cha_u_01_step2", "cha_u_01_step3", "cha_u_01_step4"], extraKey: "cha_u_01_extra" },
    { titleKey: "cha_u_02_title", objKey: "cha_u_02_obj", stepKeys: ["cha_u_02_step1", "cha_u_02_step2", "cha_u_02_step3", "cha_u_02_step4"], extraKey: "cha_u_02_extra" },
    { titleKey: "cha_u_03_title", objKey: "cha_u_03_obj", stepKeys: ["cha_u_03_step1", "cha_u_03_step2", "cha_u_03_step3"], extraKey: "cha_u_03_extra" },
    { titleKey: "cha_u_04_title", objKey: "cha_u_04_obj", stepKeys: ["cha_u_04_step1", "cha_u_04_step2", "cha_u_04_step3", "cha_u_04_step4"], extraKey: "cha_u_04_extra" },
    { titleKey: "cha_u_05_title", objKey: "cha_u_05_obj", stepKeys: ["cha_u_05_step1", "cha_u_05_step2", "cha_u_05_step3", "cha_u_05_step4"], extraKey: "cha_u_05_extra" },
    { titleKey: "cha_u_06_title", objKey: "cha_u_06_obj", stepKeys: ["cha_u_06_step1", "cha_u_06_step2", "cha_u_06_step3", "cha_u_06_step4"], extraKey: "cha_u_06_extra" },
    { titleKey: "cha_u_07_title", objKey: "cha_u_07_obj", stepKeys: ["cha_u_07_step1", "cha_u_07_step2", "cha_u_07_step3"], extraKey: "cha_u_07_extra" },
    { titleKey: "cha_u_08_title", objKey: "cha_u_08_obj", stepKeys: ["cha_u_08_step1", "cha_u_08_step2", "cha_u_08_step3"], extraKey: "cha_u_08_extra" },
    { titleKey: "cha_u_09_title", objKey: "cha_u_09_obj", stepKeys: ["cha_u_09_step1", "cha_u_09_step2", "cha_u_09_step3", "cha_u_09_step4"], extraKey: "cha_u_09_extra" },
    { titleKey: "cha_u_10_title", objKey: "cha_u_10_obj", stepKeys: ["cha_u_10_step1", "cha_u_10_step2", "cha_u_10_step3", "cha_u_10_step4"], extraKey: "cha_u_10_extra" },
    { titleKey: "cha_u_11_title", objKey: "cha_u_11_obj", stepKeys: ["cha_u_11_step1", "cha_u_11_step2", "cha_u_11_step3", "cha_u_11_step4"], extraKey: "cha_u_11_extra" },
    { titleKey: "cha_u_12_title", objKey: "cha_u_12_obj", stepKeys: ["cha_u_12_step1", "cha_u_12_step2", "cha_u_12_step3"], extraKey: "cha_u_12_extra" },
    { titleKey: "cha_u_13_title", objKey: "cha_u_13_obj", stepKeys: ["cha_u_13_step1", "cha_u_13_step2", "cha_u_13_step3"], extraKey: "cha_u_13_extra" },
    { titleKey: "cha_u_14_title", objKey: "cha_u_14_obj", stepKeys: ["cha_u_14_step1", "cha_u_14_step2", "cha_u_14_step3", "cha_u_14_step4"], extraKey: "cha_u_14_extra" },
    { titleKey: "cha_u_15_title", objKey: "cha_u_15_obj", stepKeys: ["cha_u_15_step1", "cha_u_15_step2", "cha_u_15_step3", "cha_u_15_step4"], extraKey: "cha_u_15_extra" },
    { titleKey: "cha_u_16_title", objKey: "cha_u_16_obj", stepKeys: ["cha_u_16_step1", "cha_u_16_step2", "cha_u_16_step3", "cha_u_16_step4"], extraKey: "cha_u_16_extra" },
    { titleKey: "cha_u_17_title", objKey: "cha_u_17_obj", stepKeys: ["cha_u_17_step1", "cha_u_17_step2", "cha_u_17_step3", "cha_u_17_step4"], extraKey: "cha_u_17_extra" },
    { titleKey: "cha_u_18_title", objKey: "cha_u_18_obj", stepKeys: ["cha_u_18_step1", "cha_u_18_step2", "cha_u_18_step3"], extraKey: "cha_u_18_extra" },
    { titleKey: "cha_u_19_title", objKey: "cha_u_19_obj", stepKeys: ["cha_u_19_step1", "cha_u_19_step2", "cha_u_19_step3", "cha_u_19_step4"], extraKey: "cha_u_19_extra" },
    { titleKey: "cha_u_20_title", objKey: "cha_u_20_obj", stepKeys: ["cha_u_20_step1", "cha_u_20_step2", "cha_u_20_step3", "cha_u_20_step4"], extraKey: "cha_u_20_extra" }
  ],
  group: [
    { titleKey: "cha_g_01_title", objKey: "cha_g_01_obj", stepKeys: ["cha_g_01_step1", "cha_g_01_step2", "cha_g_01_step3", "cha_g_01_step4"], extraKey: "cha_g_01_extra" },
    { titleKey: "cha_g_02_title", objKey: "cha_g_02_obj", stepKeys: ["cha_g_02_step1", "cha_g_02_step2", "cha_g_02_step3", "cha_g_02_step4"], extraKey: "cha_g_02_extra" },
    { titleKey: "cha_g_03_title", objKey: "cha_g_03_obj", stepKeys: ["cha_g_03_step1", "cha_g_03_step2", "cha_g_03_step3", "cha_g_03_step4"], extraKey: "cha_g_03_extra" },
    { titleKey: "cha_g_04_title", objKey: "cha_g_04_obj", stepKeys: ["cha_g_04_step1", "cha_g_04_step2", "cha_g_04_step3", "cha_g_04_step4"], extraKey: "cha_g_04_extra" },
    { titleKey: "cha_g_05_title", objKey: "cha_g_05_obj", stepKeys: ["cha_g_05_step1", "cha_g_05_step2", "cha_g_05_step3", "cha_g_05_step4"], extraKey: "cha_g_05_extra" },
    { titleKey: "cha_g_06_title", objKey: "cha_g_06_obj", stepKeys: ["cha_g_06_step1", "cha_g_06_step2", "cha_g_06_step3", "cha_g_06_step4"], extraKey: "cha_g_06_extra" },
    { titleKey: "cha_g_07_title", objKey: "cha_g_07_obj", stepKeys: ["cha_g_07_step1", "cha_g_07_step2", "cha_g_07_step3"], extraKey: "cha_g_07_extra" },
    { titleKey: "cha_g_08_title", objKey: "cha_g_08_obj", stepKeys: ["cha_g_08_step1", "cha_g_08_step2", "cha_g_08_step3"], extraKey: "cha_g_08_extra" },
    { titleKey: "cha_g_09_title", objKey: "cha_g_09_obj", stepKeys: ["cha_g_09_step1", "cha_g_09_step2", "cha_g_09_step3"], extraKey: "cha_g_09_extra" },
    { titleKey: "cha_g_10_title", objKey: "cha_g_10_obj", stepKeys: ["cha_g_10_step1", "cha_g_10_step2", "cha_g_10_step3"], extraKey: "cha_g_10_extra" },
    { titleKey: "cha_g_11_title", objKey: "cha_g_11_obj", stepKeys: ["cha_g_11_step1", "cha_g_11_step2", "cha_g_11_step3"], extraKey: "cha_g_11_extra" },
    { titleKey: "cha_g_12_title", objKey: "cha_g_12_obj", stepKeys: ["cha_g_12_step1", "cha_g_12_step2", "cha_g_12_step3", "cha_g_12_step4"], extraKey: "cha_g_12_extra" },
    { titleKey: "cha_g_13_title", objKey: "cha_g_13_obj", stepKeys: ["cha_g_13_step1", "cha_g_13_step2", "cha_g_13_step3"], extraKey: "cha_g_13_extra" },
    { titleKey: "cha_g_14_title", objKey: "cha_g_14_obj", stepKeys: ["cha_g_14_step1", "cha_g_14_step2", "cha_g_14_step3"], extraKey: "cha_g_14_extra" },
    { titleKey: "cha_g_15_title", objKey: "cha_g_15_obj", stepKeys: ["cha_g_15_step1", "cha_g_15_step2", "cha_g_15_step3"], extraKey: "cha_g_15_extra" },
    { titleKey: "cha_g_16_title", objKey: "cha_g_16_obj", stepKeys: ["cha_g_16_step1", "cha_g_16_step2", "cha_g_16_step3"], extraKey: "cha_g_16_extra" },
    { titleKey: "cha_g_17_title", objKey: "cha_g_17_obj", stepKeys: ["cha_g_17_step1", "cha_g_17_step2", "cha_g_17_step3"], extraKey: "cha_g_17_extra" },
    { titleKey: "cha_g_18_title", objKey: "cha_g_18_obj", stepKeys: ["cha_g_18_step1", "cha_g_18_step2", "cha_g_18_step3", "cha_g_18_step4"], extraKey: "cha_g_18_extra" },
    { titleKey: "cha_g_19_title", objKey: "cha_g_19_obj", stepKeys: ["cha_g_19_step1", "cha_g_19_step2", "cha_g_19_step3"], extraKey: "cha_g_19_extra" },
    { titleKey: "cha_g_20_title", objKey: "cha_g_20_obj", stepKeys: ["cha_g_20_step1", "cha_g_20_step2", "cha_g_20_step3"], extraKey: "cha_g_20_extra" }
    
  ],
  conflict: [
    
    { titleKey: "cha_f_01_title", objKey: "cha_f_01_obj", stepKeys: ["cha_f_01_step1", "cha_f_01_step2", "cha_f_01_step3", "cha_f_01_step4"], extraKey: "cha_f_01_extra" },
    { titleKey: "cha_f_02_title", objKey: "cha_f_02_obj", stepKeys: ["cha_f_02_step1", "cha_f_02_step2", "cha_f_02_step3", "cha_f_02_step4"], extraKey: "cha_f_02_extra" },
    { titleKey: "cha_f_03_title", objKey: "cha_f_03_obj", stepKeys: ["cha_f_03_step1", "cha_f_03_step2", "cha_f_03_step3"], extraKey: "cha_f_03_extra" },
    { titleKey: "cha_f_04_title", objKey: "cha_f_04_obj", stepKeys: ["cha_f_04_step1", "cha_f_04_step2", "cha_f_04_step3"], extraKey: "cha_f_04_extra" },
    { titleKey: "cha_f_05_title", objKey: "cha_f_05_obj", stepKeys: ["cha_f_05_step1", "cha_f_05_step2", "cha_f_05_step3", "cha_f_05_step4", "cha_f_05_step5"], extraKey: "cha_f_05_extra" },
    { titleKey: "cha_f_06_title", objKey: "cha_f_06_obj", stepKeys: ["cha_f_06_step1", "cha_f_06_step2", "cha_f_06_step3", "cha_f_06_step4"], extraKey: "cha_f_06_extra" },
    { titleKey: "cha_f_07_title", objKey: "cha_f_07_obj", stepKeys: ["cha_f_07_step1", "cha_f_07_step2", "cha_f_07_step3"], extraKey: "cha_f_07_extra" },
    { titleKey: "cha_f_08_title", objKey: "cha_f_08_obj", stepKeys: ["cha_f_08_step1", "cha_f_08_step2", "cha_f_08_step3", "cha_f_08_step4"], extraKey: "cha_f_08_extra" },
    { titleKey: "cha_f_09_title", objKey: "cha_f_09_obj", stepKeys: ["cha_f_09_step1", "cha_f_09_step2", "cha_f_09_step3"], extraKey: "cha_f_09_extra" },
    { titleKey: "cha_f_10_title", objKey: "cha_f_10_obj", stepKeys: ["cha_f_10_step1", "cha_f_10_step2", "cha_f_10_step3", "cha_f_10_step4"], extraKey: "cha_f_10_extra" },
    { titleKey: "cha_f_11_title", objKey: "cha_f_11_obj", stepKeys: ["cha_f_11_step1", "cha_f_11_step2", "cha_f_11_step3"], extraKey: "cha_f_11_extra" },
    { titleKey: "cha_f_12_title", objKey: "cha_f_12_obj", stepKeys: ["cha_f_12_step1", "cha_f_12_step2", "cha_f_12_step3", "cha_f_12_step4"], extraKey: "cha_f_12_extra" },
    { titleKey: "cha_f_13_title", objKey: "cha_f_13_obj", stepKeys: ["cha_f_13_step1", "cha_f_13_step2", "cha_f_13_step3", "cha_f_13_step4"], extraKey: "cha_f_13_extra" },
    { titleKey: "cha_f_14_title", objKey: "cha_f_14_obj", stepKeys: ["cha_f_14_step1", "cha_f_14_step2", "cha_f_14_step3"], extraKey: "cha_f_14_extra" },
    { titleKey: "cha_f_15_title", objKey: "cha_f_15_obj", stepKeys: ["cha_f_15_step1", "cha_f_15_step2", "cha_f_15_step3", "cha_f_15_step4"], extraKey: "cha_f_15_extra" },
    { titleKey: "cha_f_16_title", objKey: "cha_f_16_obj", stepKeys: ["cha_f_16_step1", "cha_f_16_step2", "cha_f_16_step3"], extraKey: "cha_f_16_extra" },
    { titleKey: "cha_f_17_title", objKey: "cha_f_17_obj", stepKeys: ["cha_f_17_step1", "cha_f_17_step2", "cha_f_17_step3", "cha_f_17_step4"], extraKey: "cha_f_17_extra" },
    { titleKey: "cha_f_18_title", objKey: "cha_f_18_obj", stepKeys: ["cha_f_18_step1", "cha_f_18_step2", "cha_f_18_step3", "cha_f_18_step4"], extraKey: "cha_f_18_extra" },
    { titleKey: "cha_f_19_title", objKey: "cha_f_19_obj", stepKeys: ["cha_f_19_step1", "cha_f_19_step2", "cha_f_19_step3", "cha_f_19_step4"], extraKey: "cha_f_19_extra" },
    { titleKey: "cha_f_20_title", objKey: "cha_f_20_obj", stepKeys: ["cha_f_20_step1", "cha_f_20_step2", "cha_f_20_step3"], extraKey: "cha_f_20_extra" }
  ],
};
 

const regulations = [
  // --- ITENS 1-20 CONVERTIDOS ---
  { titleKey: "reg_01_title", descKey: "reg_01_desc", stepKeys: ["reg_01_step1", "reg_01_step2", "reg_01_step3", "reg_01_step4", "reg_01_step5"] },
  { titleKey: "reg_02_title", descKey: "reg_02_desc", stepKeys: ["reg_02_step1", "reg_02_step2", "reg_02_step3", "reg_02_step4", "reg_02_step5", "reg_02_step6"] },
  { titleKey: "reg_03_title", descKey: "reg_03_desc", stepKeys: ["reg_03_step1", "reg_03_step2", "reg_03_step3", "reg_03_step4", "reg_03_step5"] },
  { titleKey: "reg_04_title", descKey: "reg_04_desc", stepKeys: ["reg_04_step1", "reg_04_step2", "reg_04_step3", "reg_04_step4", "reg_04_step5"] },
  { titleKey: "reg_05_title", descKey: "reg_05_desc", stepKeys: ["reg_05_step1", "reg_05_step2", "reg_05_step3", "reg_05_step4", "reg_05_step5"] },
  { titleKey: "reg_06_title", descKey: "reg_06_desc", stepKeys: ["reg_06_step1", "reg_06_step2", "reg_06_step3", "reg_06_step4"] },
  { titleKey: "reg_07_title", descKey: "reg_07_desc", stepKeys: ["reg_07_step1", "reg_07_step2", "reg_07_step3", "reg_07_step4", "reg_07_step5"] },
  { titleKey: "reg_08_title", descKey: "reg_08_desc", stepKeys: ["reg_08_step1", "reg_08_step2", "reg_08_step3", "reg_08_step4", "reg_08_step5"] },
  { titleKey: "reg_09_title", descKey: "reg_09_desc", stepKeys: ["reg_09_step1", "reg_09_step2", "reg_09_step3", "reg_09_step4", "reg_09_step5"] },
  { titleKey: "reg_10_title", descKey: "reg_10_desc", stepKeys: ["reg_10_step1", "reg_10_step2", "reg_10_step3", "reg_10_step4"] },
  { titleKey: "reg_11_title", descKey: "reg_11_desc", stepKeys: ["reg_11_step1", "reg_11_step2", "reg_11_step3", "reg_11_step4", "reg_11_step5"] },
  { titleKey: "reg_12_title", descKey: "reg_12_desc", stepKeys: ["reg_12_step1", "reg_12_step2", "reg_12_step3", "reg_12_step4"] },
  { titleKey: "reg_13_title", descKey: "reg_13_desc", stepKeys: ["reg_13_step1", "reg_13_step2", "reg_13_step3", "reg_13_step4", "reg_13_step5"] },
  { titleKey: "reg_14_title", descKey: "reg_14_desc", stepKeys: ["reg_14_step1", "reg_14_step2", "reg_14_step3", "reg_14_step4"] },
  { titleKey: "reg_15_title", descKey: "reg_15_desc", stepKeys: ["reg_15_step1", "reg_15_step2", "reg_15_step3", "reg_15_step4", "reg_15_step5"] },
  { titleKey: "reg_16_title", descKey: "reg_16_desc", stepKeys: ["reg_16_step1", "reg_16_step2", "reg_16_step3", "reg_16_step4"] },
  { titleKey: "reg_17_title", descKey: "reg_17_desc", stepKeys: ["reg_17_step1", "reg_17_step2", "reg_17_step3", "reg_17_step4"] },
  { titleKey: "reg_18_title", descKey: "reg_18_desc", stepKeys: ["reg_18_step1", "reg_18_step2", "reg_18_step3", "reg_18_step4"] },
  { titleKey: "reg_19_title", descKey: "reg_19_desc", stepKeys: ["reg_19_step1", "reg_19_step2", "reg_19_step3", "reg_19_step4", "reg_19_step5"] },
  { titleKey: "reg_20_title", descKey: "reg_20_desc", stepKeys: ["reg_20_step1", "reg_20_step2", "reg_20_step3", "reg_20_step4", "reg_20_step5"] },
  // --- ITENS 21-40 (CONVERTIDOS AGORA) ---
  { titleKey: "reg_21_title", descKey: "reg_21_desc", stepKeys: ["reg_21_step1", "reg_21_step2", "reg_21_step3", "reg_21_step4"] },
  { titleKey: "reg_22_title", descKey: "reg_22_desc", stepKeys: ["reg_22_step1", "reg_22_step2", "reg_22_step3", "reg_22_step4", "reg_22_step5"] },
  { titleKey: "reg_23_title", descKey: "reg_23_desc", stepKeys: ["reg_23_step1", "reg_23_step2", "reg_23_step3", "reg_23_step4"] },
  { titleKey: "reg_24_title", descKey: "reg_24_desc", stepKeys: ["reg_24_step1", "reg_24_step2", "reg_24_step3", "reg_24_step4"] },
  { titleKey: "reg_25_title", descKey: "reg_25_desc", stepKeys: ["reg_25_step1", "reg_25_step2", "reg_25_step3", "reg_25_step4"] },
  { titleKey: "reg_26_title", descKey: "reg_26_desc", stepKeys: ["reg_26_step1", "reg_26_step2", "reg_26_step3", "reg_26_step4"] },
  { titleKey: "reg_27_title", descKey: "reg_27_desc", stepKeys: ["reg_27_step1", "reg_27_step2", "reg_27_step3", "reg_27_step4", "reg_27_step5"] },
  { titleKey: "reg_28_title", descKey: "reg_28_desc", stepKeys: ["reg_28_step1", "reg_28_step2", "reg_28_step3", "reg_28_step4", "reg_28_step5"] },
  { titleKey: "reg_29_title", descKey: "reg_29_desc", stepKeys: ["reg_29_step1", "reg_29_step2", "reg_29_step3", "reg_29_step4", "reg_29_step5"] },
  { titleKey: "reg_30_title", descKey: "reg_30_desc", stepKeys: ["reg_30_step1", "reg_30_step2", "reg_30_step3", "reg_30_step4"] },
  { titleKey: "reg_31_title", descKey: "reg_31_desc", stepKeys: ["reg_31_step1", "reg_31_step2", "reg_31_step3", "reg_31_step4", "reg_31_step5"] },
  { titleKey: "reg_32_title", descKey: "reg_32_desc", stepKeys: ["reg_32_step1", "reg_32_step2", "reg_32_step3", "reg_32_step4", "reg_32_step5"] },
  { titleKey: "reg_33_title", descKey: "reg_33_desc", stepKeys: ["reg_33_step1", "reg_33_step2", "reg_33_step3", "reg_33_step4", "reg_33_step5"] },
  { titleKey: "reg_34_title", descKey: "reg_34_desc", stepKeys: ["reg_34_step1", "reg_34_step2", "reg_34_step3", "reg_34_step4"] },
  { titleKey: "reg_35_title", descKey: "reg_35_desc", stepKeys: ["reg_35_step1", "reg_35_step2", "reg_35_step3", "reg_35_step4", "reg_35_step5"] },
  { titleKey: "reg_36_title", descKey: "reg_36_desc", stepKeys: ["reg_36_step1", "reg_36_step2", "reg_36_step3", "reg_36_step4"] },
  { titleKey: "reg_37_title", descKey: "reg_37_desc", stepKeys: ["reg_37_step1", "reg_37_step2", "reg_37_step3", "reg_37_step4", "reg_37_step5"] },
  { titleKey: "reg_38_title", descKey: "reg_38_desc", stepKeys: ["reg_38_step1", "reg_38_step2", "reg_38_step3", "reg_38_step4", "reg_38_step5"] },
  { titleKey: "reg_39_title", descKey: "reg_39_desc", stepKeys: ["reg_39_step1", "reg_39_step2", "reg_39_step3", "reg_39_step4", "reg_39_step5"] },
  { titleKey: "reg_40_title", descKey: "reg_40_desc", stepKeys: ["reg_40_step1", "reg_40_step2", "reg_40_step3", "reg_40_step4"] },
  // --- ITENS 41-60 (CONVERTIDOS AGORA) ---
  { titleKey: "reg_41_title", descKey: "reg_41_desc", stepKeys: ["reg_41_step1", "reg_41_step2", "reg_41_step3", "reg_41_step4", "reg_41_step5"] },
  { titleKey: "reg_42_title", descKey: "reg_42_desc", stepKeys: ["reg_42_step1", "reg_42_step2", "reg_42_step3", "reg_42_step4", "reg_42_step5"] },
  { titleKey: "reg_43_title", descKey: "reg_43_desc", stepKeys: ["reg_43_step1", "reg_43_step2", "reg_43_step3", "reg_43_step4"] },
  { titleKey: "reg_44_title", descKey: "reg_44_desc", stepKeys: ["reg_44_step1", "reg_44_step2", "reg_44_step3", "reg_44_step4", "reg_44_step5"] },
  { titleKey: "reg_45_title", descKey: "reg_45_desc", stepKeys: ["reg_45_step1", "reg_45_step2", "reg_45_step3", "reg_45_step4"] },
  { titleKey: "reg_46_title", descKey: "reg_46_desc", stepKeys: ["reg_46_step1", "reg_46_step2", "reg_46_step3", "reg_46_step4"] },
  { titleKey: "reg_47_title", descKey: "reg_47_desc", stepKeys: ["reg_47_step1", "reg_47_step2", "reg_47_step3", "reg_47_step4"] },
  { titleKey: "reg_48_title", descKey: "reg_48_desc", stepKeys: ["reg_48_step1", "reg_48_step2", "reg_48_step3", "reg_48_step4"] },
  { titleKey: "reg_49_title", descKey: "reg_49_desc", stepKeys: ["reg_49_step1", "reg_49_step2", "reg_49_step3", "reg_49_step4"] },
  { titleKey: "reg_50_title", descKey: "reg_50_desc", stepKeys: ["reg_50_step1", "reg_50_step2", "reg_50_step3", "reg_50_step4"] },
  { titleKey: "reg_51_title", descKey: "reg_51_desc", stepKeys: ["reg_51_step1", "reg_51_step2", "reg_51_step3", "reg_51_step4"] },
  { titleKey: "reg_52_title", descKey: "reg_52_desc", stepKeys: ["reg_52_step1", "reg_52_step2", "reg_52_step3", "reg_52_step4"] },
  { titleKey: "reg_53_title", descKey: "reg_53_desc", stepKeys: ["reg_53_step1", "reg_53_step2", "reg_53_step3", "reg_53_step4"] },
  { titleKey: "reg_54_title", descKey: "reg_54_desc", stepKeys: ["reg_54_step1", "reg_54_step2", "reg_54_step3", "reg_54_step4"] },
  { titleKey: "reg_55_title", descKey: "reg_55_desc", stepKeys: ["reg_55_step1", "reg_55_step2", "reg_55_step3", "reg_55_step4", "reg_55_step5"] },
  { titleKey: "reg_56_title", descKey: "reg_56_desc", stepKeys: ["reg_56_step1", "reg_56_step2", "reg_56_step3", "reg_56_step4"] },
  { titleKey: "reg_57_title", descKey: "reg_57_desc", stepKeys: ["reg_57_step1", "reg_57_step2", "reg_57_step3", "reg_57_step4", "reg_57_step5"] },
  { titleKey: "reg_58_title", descKey: "reg_58_desc", stepKeys: ["reg_58_step1", "reg_58_step2", "reg_58_step3", "reg_58_step4", "reg_58_step5"] },
  { titleKey: "reg_59_title", descKey: "reg_59_desc", stepKeys: ["reg_59_step1", "reg_59_step2", "reg_59_step3", "reg_59_step4", "reg_59_step5"] },
  { titleKey: "reg_60_title", descKey: "reg_60_desc", stepKeys: ["reg_60_step1", "reg_60_step2", "reg_60_step3", "reg_60_step4", "reg_60_step5"] },
  { titleKey: "reg_61_title", descKey: "reg_61_desc", stepKeys: ["reg_61_step1", "reg_61_step2", "reg_61_step3", "reg_61_step4", "reg_61_step5"] },
  { titleKey: "reg_62_title", descKey: "reg_62_desc", stepKeys: ["reg_62_step1", "reg_62_step2", "reg_62_step3", "reg_62_step4", "reg_62_step5", "reg_62_step6"] },
  { titleKey: "reg_63_title", descKey: "reg_63_desc", stepKeys: ["reg_63_step1", "reg_63_step2", "reg_63_step3", "reg_63_step4", "reg_63_step5", "reg_63_step6"] },
  { titleKey: "reg_64_title", descKey: "reg_64_desc", stepKeys: ["reg_64_step1", "reg_64_step2", "reg_64_step3", "reg_64_step4", "reg_64_step5"] },
  { titleKey: "reg_65_title", descKey: "reg_65_desc", stepKeys: ["reg_65_step1", "reg_65_step2", "reg_65_step3", "reg_65_step4", "reg_65_step5"] },
  { titleKey: "reg_66_title", descKey: "reg_66_desc", stepKeys: ["reg_66_step1", "reg_66_step2", "reg_66_step3", "reg_66_step4"] },
  { titleKey: "reg_67_title", descKey: "reg_67_desc", stepKeys: ["reg_67_step1", "reg_67_step2", "reg_67_step3", "reg_67_step4", "reg_67_step5"] },
  { titleKey: "reg_68_title", descKey: "reg_68_desc", stepKeys: ["reg_68_step1", "reg_68_step2", "reg_68_step3", "reg_68_step4"] },
  { titleKey: "reg_69_title", descKey: "reg_69_desc", stepKeys: ["reg_69_step1", "reg_69_step2", "reg_69_step3", "reg_69_step4", "reg_69_step5", "reg_69_step6"] }
  



];


export {
  expressions as mockExpressions,
  motivation as mockMotivation,
  bible as mockBible,
  challenges as mockChallenges,
  regulations as mockRegulations
};